// Code generated by ak-ops/contracts/canonical/v1/generator; DO NOT EDIT.
// Source schema set: sha256:659fe8c948d522801ddf7082d4dd19e6203e8293b0c02b4d44005f98ca874c62

package canonicalcontract

import (
	"bytes"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode/utf16"
	"unicode/utf8"

	"golang.org/x/text/unicode/norm"
)

const (
	CanonicalJSONVersion       = "ak.canonical.json.v1"
	CanonicalRawVersion        = "ak.canonical.raw.v1"
	HashAlgorithm              = "sha256"
	HashPrefix                 = "sha256:"
	MaxSafeInteger       int64 = 9007199254740991
)

type ResultCode string

const (
	ValidContract          ResultCode = "VALID_CONTRACT"
	InvalidSyntax          ResultCode = "INVALID_SYNTAX"
	InvalidSchema          ResultCode = "INVALID_SCHEMA"
	InvalidCanonicalForm   ResultCode = "INVALID_CANONICAL_FORM"
	HashMismatch           ResultCode = "HASH_MISMATCH"
	CrossReferenceMismatch ResultCode = "CROSS_REFERENCE_MISMATCH"
	UnsupportedVersion     ResultCode = "UNSUPPORTED_VERSION"
	ResourceLimitExceeded  ResultCode = "RESOURCE_LIMIT_EXCEEDED"
)

type ErrorCode string

const (
	CodeNone                     ErrorCode = "NONE"
	CodeDocumentTooLarge         ErrorCode = "DOCUMENT_TOO_LARGE"
	CodeNestingTooDeep           ErrorCode = "NESTING_TOO_DEEP"
	CodeTooManyFields            ErrorCode = "TOO_MANY_FIELDS"
	CodeArrayTooLong             ErrorCode = "ARRAY_TOO_LONG"
	CodeStringTooLong            ErrorCode = "STRING_TOO_LONG"
	CodeInvalidUTF8              ErrorCode = "INVALID_UTF8"
	CodeBOM                      ErrorCode = "BYTE_ORDER_MARK"
	CodeUnexpectedEOF            ErrorCode = "UNEXPECTED_EOF"
	CodeUnexpectedToken          ErrorCode = "UNEXPECTED_TOKEN"
	CodeInvalidEscape            ErrorCode = "INVALID_ESCAPE"
	CodeInvalidUnicode           ErrorCode = "INVALID_UNICODE"
	CodeNonNFC                   ErrorCode = "NON_NFC_STRING"
	CodeDuplicateKey             ErrorCode = "DUPLICATE_KEY"
	CodeTrailingData             ErrorCode = "TRAILING_DATA"
	CodeInvalidNumber            ErrorCode = "INVALID_NUMBER"
	CodeFloatingPointForbidden   ErrorCode = "FLOATING_POINT_FORBIDDEN"
	CodeUnsafeInteger            ErrorCode = "UNSAFE_INTEGER"
	CodeProhibitedNull           ErrorCode = "PROHIBITED_NULL"
	CodeMissingRequiredField     ErrorCode = "MISSING_REQUIRED_FIELD"
	CodeUnknownField             ErrorCode = "UNKNOWN_FIELD"
	CodeTypeMismatch             ErrorCode = "TYPE_MISMATCH"
	CodeInvalidConstant          ErrorCode = "INVALID_CONSTANT"
	CodeInvalidEnum              ErrorCode = "INVALID_ENUM"
	CodeInvalidPattern           ErrorCode = "INVALID_PATTERN"
	CodeInvalidLength            ErrorCode = "INVALID_LENGTH"
	CodeInvalidRange             ErrorCode = "INVALID_RANGE"
	CodeDuplicateSetMember       ErrorCode = "DUPLICATE_SET_MEMBER"
	CodeNonCanonicalSetOrder     ErrorCode = "NONCANONICAL_SET_ORDER"
	CodeUnknownContract          ErrorCode = "UNKNOWN_CONTRACT"
	CodeSchemaVersionMismatch    ErrorCode = "SCHEMA_VERSION_MISMATCH"
	CodeCanonicalVersionMismatch ErrorCode = "CANONICALIZATION_VERSION_MISMATCH"
	CodeHashAlgorithmMismatch    ErrorCode = "HASH_ALGORITHM_MISMATCH"
	CodeArtifactRoleMismatch     ErrorCode = "ARTIFACT_ROLE_MISMATCH"
	CodeInvalidHash              ErrorCode = "INVALID_HASH"
	CodeInvalidTimestamp         ErrorCode = "INVALID_TIMESTAMP"
	CodeInvalidDecimal           ErrorCode = "INVALID_DECIMAL"
	CodeInvalidPath              ErrorCode = "INVALID_PATH"
	CodeNonCanonicalBytes        ErrorCode = "NONCANONICAL_BYTES"
	CodeSelfHashMismatch         ErrorCode = "SELF_HASH_MISMATCH"
	CodeRawHashMismatch          ErrorCode = "RAW_HASH_MISMATCH"
	CodeReferenceHashMismatch    ErrorCode = "REFERENCE_HASH_MISMATCH"
	CodeSemanticViolation        ErrorCode = "SEMANTIC_VIOLATION"
)

type ContractError struct {
	Result ResultCode
	Code   ErrorCode
	Path   string
	Offset int
	Err    error
}

func (e *ContractError) Error() string {
	if e == nil {
		return ""
	}
	location := e.Path
	if location == "" {
		location = "$"
	}
	if e.Offset >= 0 {
		location += fmt.Sprintf("@%d", e.Offset)
	}
	if e.Err == nil {
		return fmt.Sprintf("%s/%s at %s", e.Result, e.Code, location)
	}
	return fmt.Sprintf("%s/%s at %s: %v", e.Result, e.Code, location, e.Err)
}

func (e *ContractError) Unwrap() error { return e.Err }

func contractError(result ResultCode, code ErrorCode, offset int, path string, err error) error {
	return &ContractError{Result: result, Code: code, Offset: offset, Path: path, Err: err}
}

func Classify(err error) (ResultCode, ErrorCode) {
	if err == nil {
		return ValidContract, CodeNone
	}
	var target *ContractError
	if errors.As(err, &target) {
		return target.Result, target.Code
	}
	return InvalidSchema, CodeSemanticViolation
}

type Limits struct {
	MaxDocumentBytes int
	MaxNestingDepth  int
	MaxFieldCount    int
	MaxArrayLength   int
	MaxStringBytes   int
}

var DefaultLimits = Limits{
	MaxDocumentBytes: 1_048_576,
	MaxNestingDepth:  64,
	MaxFieldCount:    20_000,
	MaxArrayLength:   10_000,
	MaxStringBytes:   65_536,
}

type Kind uint8

const (
	KindObject Kind = iota + 1
	KindArray
	KindString
	KindNumber
	KindBoolean
	KindNull
)

type Member struct {
	Key   string
	Value *Value
}

type Value struct {
	Kind   Kind
	Object []Member
	Array  []*Value
	String string
	Number string
	Bool   bool
}

func (v *Value) Member(name string) (*Value, bool) {
	if v == nil || v.Kind != KindObject {
		return nil, false
	}
	for _, member := range v.Object {
		if member.Key == name {
			return member.Value, true
		}
	}
	return nil, false
}

func (v *Value) cloneWithoutTopLevelMember(name string) (*Value, error) {
	if v == nil || v.Kind != KindObject {
		return nil, contractError(InvalidSchema, CodeTypeMismatch, -1, "$", errors.New("artifact root must be an object"))
	}
	clone := *v
	clone.Object = make([]Member, 0, len(v.Object)-1)
	found := false
	for _, member := range v.Object {
		if member.Key == name {
			found = true
			continue
		}
		clone.Object = append(clone.Object, member)
	}
	if !found {
		return nil, contractError(InvalidSchema, CodeMissingRequiredField, -1, "$.'"+name+"'", errors.New("self-hash member is missing"))
	}
	return &clone, nil
}

type parser struct {
	data       []byte
	pos        int
	limits     Limits
	fieldCount int
}

func Parse(data []byte) (*Value, error) { return ParseWithLimits(data, DefaultLimits) }

func ParseWithLimits(data []byte, limits Limits) (*Value, error) {
	if limits.MaxDocumentBytes <= 0 || limits.MaxNestingDepth <= 0 || limits.MaxFieldCount <= 0 || limits.MaxArrayLength <= 0 || limits.MaxStringBytes <= 0 {
		return nil, contractError(InvalidSchema, CodeSemanticViolation, -1, "$", errors.New("resource limits must be positive"))
	}
	if len(data) > limits.MaxDocumentBytes {
		return nil, contractError(ResourceLimitExceeded, CodeDocumentTooLarge, len(data), "$", fmt.Errorf("maximum is %d bytes", limits.MaxDocumentBytes))
	}
	if len(data) >= 3 && bytes.Equal(data[:3], []byte{0xef, 0xbb, 0xbf}) {
		return nil, contractError(InvalidSyntax, CodeBOM, 0, "$", errors.New("UTF-8 BOM is forbidden"))
	}
	if !utf8.Valid(data) {
		return nil, contractError(InvalidSyntax, CodeInvalidUTF8, 0, "$", errors.New("input is not valid UTF-8"))
	}
	p := &parser{data: data, limits: limits}
	p.skipWhitespace()
	value, err := p.parseValue(1, "$")
	if err != nil {
		return nil, err
	}
	p.skipWhitespace()
	if p.pos != len(p.data) {
		return nil, contractError(InvalidSyntax, CodeTrailingData, p.pos, "$", errors.New("trailing JSON data"))
	}
	return value, nil
}

func (p *parser) parseValue(depth int, path string) (*Value, error) {
	if depth > p.limits.MaxNestingDepth {
		return nil, contractError(ResourceLimitExceeded, CodeNestingTooDeep, p.pos, path, fmt.Errorf("maximum depth is %d", p.limits.MaxNestingDepth))
	}
	if p.pos >= len(p.data) {
		return nil, contractError(InvalidSyntax, CodeUnexpectedEOF, p.pos, path, errors.New("expected JSON value"))
	}
	switch p.data[p.pos] {
	case '{':
		return p.parseObject(depth, path)
	case '[':
		return p.parseArray(depth, path)
	case '"':
		value, err := p.parseString(path)
		if err != nil {
			return nil, err
		}
		return &Value{Kind: KindString, String: value}, nil
	case 't':
		return p.parseLiteral("true", &Value{Kind: KindBoolean, Bool: true}, path)
	case 'f':
		return p.parseLiteral("false", &Value{Kind: KindBoolean}, path)
	case 'n':
		return p.parseLiteral("null", &Value{Kind: KindNull}, path)
	default:
		if p.data[p.pos] == '-' || p.data[p.pos] >= '0' && p.data[p.pos] <= '9' {
			return p.parseNumber(path)
		}
		return nil, contractError(InvalidSyntax, CodeUnexpectedToken, p.pos, path, fmt.Errorf("unexpected byte %q", p.data[p.pos]))
	}
}

func (p *parser) parseObject(depth int, path string) (*Value, error) {
	p.pos++
	p.skipWhitespace()
	result := &Value{Kind: KindObject}
	seen := map[string]struct{}{}
	if p.consume('}') {
		return result, nil
	}
	for {
		if p.pos >= len(p.data) || p.data[p.pos] != '"' {
			return nil, contractError(InvalidSyntax, CodeUnexpectedToken, p.pos, path, errors.New("object key must be a string"))
		}
		keyOffset := p.pos
		key, err := p.parseString(path)
		if err != nil {
			return nil, err
		}
		if _, exists := seen[key]; exists {
			return nil, contractError(InvalidSyntax, CodeDuplicateKey, keyOffset, path, fmt.Errorf("duplicate key %q", key))
		}
		seen[key] = struct{}{}
		p.fieldCount++
		if p.fieldCount > p.limits.MaxFieldCount {
			return nil, contractError(ResourceLimitExceeded, CodeTooManyFields, p.pos, path, fmt.Errorf("maximum field count is %d", p.limits.MaxFieldCount))
		}
		p.skipWhitespace()
		if !p.consume(':') {
			return nil, contractError(InvalidSyntax, CodeUnexpectedToken, p.pos, path, errors.New("expected colon after object key"))
		}
		p.skipWhitespace()
		childPath := path + "." + key
		value, err := p.parseValue(depth+1, childPath)
		if err != nil {
			return nil, err
		}
		result.Object = append(result.Object, Member{Key: key, Value: value})
		p.skipWhitespace()
		if p.consume('}') {
			return result, nil
		}
		if !p.consume(',') {
			return nil, contractError(InvalidSyntax, CodeUnexpectedToken, p.pos, path, errors.New("expected comma or object end"))
		}
		p.skipWhitespace()
	}
}

func (p *parser) parseArray(depth int, path string) (*Value, error) {
	p.pos++
	p.skipWhitespace()
	result := &Value{Kind: KindArray}
	if p.consume(']') {
		return result, nil
	}
	for {
		if len(result.Array) >= p.limits.MaxArrayLength {
			return nil, contractError(ResourceLimitExceeded, CodeArrayTooLong, p.pos, path, fmt.Errorf("maximum array length is %d", p.limits.MaxArrayLength))
		}
		childPath := fmt.Sprintf("%s[%d]", path, len(result.Array))
		value, err := p.parseValue(depth+1, childPath)
		if err != nil {
			return nil, err
		}
		result.Array = append(result.Array, value)
		p.skipWhitespace()
		if p.consume(']') {
			return result, nil
		}
		if !p.consume(',') {
			return nil, contractError(InvalidSyntax, CodeUnexpectedToken, p.pos, path, errors.New("expected comma or array end"))
		}
		p.skipWhitespace()
	}
}

func (p *parser) parseString(path string) (string, error) {
	start := p.pos
	p.pos++
	var result strings.Builder
	for p.pos < len(p.data) {
		b := p.data[p.pos]
		if b == '"' {
			p.pos++
			value := result.String()
			if len(value) > p.limits.MaxStringBytes {
				return "", contractError(ResourceLimitExceeded, CodeStringTooLong, start, path, fmt.Errorf("maximum string size is %d", p.limits.MaxStringBytes))
			}
			if !norm.NFC.IsNormalString(value) {
				return "", contractError(InvalidSyntax, CodeNonNFC, start, path, errors.New("string is not Unicode NFC"))
			}
			return value, nil
		}
		if b == '\\' {
			p.pos++
			if p.pos >= len(p.data) {
				return "", contractError(InvalidSyntax, CodeUnexpectedEOF, p.pos, path, errors.New("incomplete escape"))
			}
			switch p.data[p.pos] {
			case '"', '\\', '/':
				result.WriteByte(p.data[p.pos])
				p.pos++
			case 'b':
				result.WriteByte('\b')
				p.pos++
			case 'f':
				result.WriteByte('\f')
				p.pos++
			case 'n':
				result.WriteByte('\n')
				p.pos++
			case 'r':
				result.WriteByte('\r')
				p.pos++
			case 't':
				result.WriteByte('\t')
				p.pos++
			case 'u':
				r, err := p.parseUnicodeEscape(path)
				if err != nil {
					return "", err
				}
				result.WriteRune(r)
			default:
				return "", contractError(InvalidSyntax, CodeInvalidEscape, p.pos, path, fmt.Errorf("invalid escape %q", p.data[p.pos]))
			}
			continue
		}
		if b < 0x20 {
			return "", contractError(InvalidSyntax, CodeUnexpectedToken, p.pos, path, errors.New("unescaped control character"))
		}
		r, size := utf8.DecodeRune(p.data[p.pos:])
		if r == utf8.RuneError && size == 1 {
			return "", contractError(InvalidSyntax, CodeInvalidUTF8, p.pos, path, errors.New("invalid UTF-8 in string"))
		}
		if isForbiddenUnicode(r) {
			return "", contractError(InvalidSyntax, CodeInvalidUnicode, p.pos, path, fmt.Errorf("forbidden code point U+%04X", r))
		}
		result.WriteRune(r)
		p.pos += size
	}
	return "", contractError(InvalidSyntax, CodeUnexpectedEOF, p.pos, path, errors.New("unterminated string"))
}

func (p *parser) parseUnicodeEscape(path string) (rune, error) {
	first, err := p.readHexEscape(path)
	if err != nil {
		return 0, err
	}
	if first >= 0xd800 && first <= 0xdbff {
		if p.pos+2 > len(p.data) || p.data[p.pos] != '\\' || p.data[p.pos+1] != 'u' {
			return 0, contractError(InvalidSyntax, CodeInvalidUnicode, p.pos, path, errors.New("high surrogate lacks low surrogate"))
		}
		p.pos++
		second, err := p.readHexEscape(path)
		if err != nil {
			return 0, err
		}
		if second < 0xdc00 || second > 0xdfff {
			return 0, contractError(InvalidSyntax, CodeInvalidUnicode, p.pos, path, errors.New("invalid low surrogate"))
		}
		r := utf16.DecodeRune(rune(first), rune(second))
		if isForbiddenUnicode(r) {
			return 0, contractError(InvalidSyntax, CodeInvalidUnicode, p.pos, path, fmt.Errorf("forbidden code point U+%04X", r))
		}
		return r, nil
	}
	if first >= 0xdc00 && first <= 0xdfff {
		return 0, contractError(InvalidSyntax, CodeInvalidUnicode, p.pos, path, errors.New("unpaired low surrogate"))
	}
	r := rune(first)
	if isForbiddenUnicode(r) {
		return 0, contractError(InvalidSyntax, CodeInvalidUnicode, p.pos, path, fmt.Errorf("forbidden code point U+%04X", r))
	}
	return r, nil
}

func (p *parser) readHexEscape(path string) (uint16, error) {
	if p.pos >= len(p.data) || p.data[p.pos] != 'u' || p.pos+5 > len(p.data) {
		return 0, contractError(InvalidSyntax, CodeInvalidEscape, p.pos, path, errors.New("incomplete Unicode escape"))
	}
	p.pos++
	var value uint16
	for i := 0; i < 4; i++ {
		nibble, ok := hexNibble(p.data[p.pos+i])
		if !ok {
			return 0, contractError(InvalidSyntax, CodeInvalidEscape, p.pos+i, path, errors.New("invalid hexadecimal escape"))
		}
		value = value<<4 | uint16(nibble)
	}
	p.pos += 4
	return value, nil
}

func (p *parser) parseNumber(path string) (*Value, error) {
	start := p.pos
	if p.consume('-') && p.pos >= len(p.data) {
		return nil, contractError(InvalidSyntax, CodeInvalidNumber, start, path, errors.New("incomplete number"))
	}
	if p.consume('0') {
		if p.pos < len(p.data) && p.data[p.pos] >= '0' && p.data[p.pos] <= '9' {
			return nil, contractError(InvalidSyntax, CodeInvalidNumber, start, path, errors.New("leading zero"))
		}
	} else {
		if p.pos >= len(p.data) || p.data[p.pos] < '1' || p.data[p.pos] > '9' {
			return nil, contractError(InvalidSyntax, CodeInvalidNumber, start, path, errors.New("invalid integer part"))
		}
		for p.pos < len(p.data) && p.data[p.pos] >= '0' && p.data[p.pos] <= '9' {
			p.pos++
		}
	}
	if p.consume('.') {
		if p.pos >= len(p.data) || p.data[p.pos] < '0' || p.data[p.pos] > '9' {
			return nil, contractError(InvalidSyntax, CodeInvalidNumber, start, path, errors.New("fraction has no digits"))
		}
		for p.pos < len(p.data) && p.data[p.pos] >= '0' && p.data[p.pos] <= '9' {
			p.pos++
		}
	}
	if p.pos < len(p.data) && (p.data[p.pos] == 'e' || p.data[p.pos] == 'E') {
		p.pos++
		if p.pos < len(p.data) && (p.data[p.pos] == '+' || p.data[p.pos] == '-') {
			p.pos++
		}
		if p.pos >= len(p.data) || p.data[p.pos] < '0' || p.data[p.pos] > '9' {
			return nil, contractError(InvalidSyntax, CodeInvalidNumber, start, path, errors.New("exponent has no digits"))
		}
		for p.pos < len(p.data) && p.data[p.pos] >= '0' && p.data[p.pos] <= '9' {
			p.pos++
		}
	}
	return &Value{Kind: KindNumber, Number: string(p.data[start:p.pos])}, nil
}

func (p *parser) parseLiteral(literal string, value *Value, path string) (*Value, error) {
	if p.pos+len(literal) > len(p.data) || string(p.data[p.pos:p.pos+len(literal)]) != literal {
		return nil, contractError(InvalidSyntax, CodeUnexpectedToken, p.pos, path, fmt.Errorf("expected %s", literal))
	}
	p.pos += len(literal)
	return value, nil
}

func (p *parser) skipWhitespace() {
	for p.pos < len(p.data) {
		switch p.data[p.pos] {
		case ' ', '\t', '\r', '\n':
			p.pos++
		default:
			return
		}
	}
}

func (p *parser) consume(expected byte) bool {
	if p.pos < len(p.data) && p.data[p.pos] == expected {
		p.pos++
		return true
	}
	return false
}

func hexNibble(value byte) (byte, bool) {
	switch {
	case value >= '0' && value <= '9':
		return value - '0', true
	case value >= 'a' && value <= 'f':
		return value - 'a' + 10, true
	case value >= 'A' && value <= 'F':
		return value - 'A' + 10, true
	default:
		return 0, false
	}
}

func isForbiddenUnicode(r rune) bool {
	return r >= 0xfdd0 && r <= 0xfdef || r&0xffff == 0xfffe || r&0xffff == 0xffff
}

func Canonicalize(data []byte) ([]byte, error) {
	value, err := Parse(data)
	if err != nil {
		return nil, err
	}
	return value.CanonicalBytes()
}

func CanonicalizeValue(value any) ([]byte, error) {
	raw, err := json.Marshal(value)
	if err != nil {
		return nil, contractError(InvalidSchema, CodeTypeMismatch, -1, "$", err)
	}
	return Canonicalize(raw)
}

func (v *Value) CanonicalBytes() ([]byte, error) {
	var out bytes.Buffer
	if err := appendCanonical(&out, v, "$", 1); err != nil {
		return nil, err
	}
	return out.Bytes(), nil
}

func appendCanonical(out *bytes.Buffer, value *Value, path string, depth int) error {
	if value == nil {
		return contractError(InvalidSchema, CodeTypeMismatch, -1, path, errors.New("nil value"))
	}
	switch value.Kind {
	case KindObject:
		members := append([]Member(nil), value.Object...)
		sortMembersUTF16(members)
		out.WriteByte('{')
		for i, member := range members {
			if i > 0 {
				out.WriteByte(',')
			}
			appendCanonicalString(out, member.Key)
			out.WriteByte(':')
			if err := appendCanonical(out, member.Value, path+"."+member.Key, depth+1); err != nil {
				return err
			}
		}
		out.WriteByte('}')
	case KindArray:
		out.WriteByte('[')
		for i, item := range value.Array {
			if i > 0 {
				out.WriteByte(',')
			}
			if err := appendCanonical(out, item, fmt.Sprintf("%s[%d]", path, i), depth+1); err != nil {
				return err
			}
		}
		out.WriteByte(']')
	case KindString:
		appendCanonicalString(out, value.String)
	case KindNumber:
		canonical, err := canonicalInteger(value.Number, path)
		if err != nil {
			return err
		}
		out.WriteString(canonical)
	case KindBoolean:
		if value.Bool {
			out.WriteString("true")
		} else {
			out.WriteString("false")
		}
	case KindNull:
		out.WriteString("null")
	default:
		return contractError(InvalidSchema, CodeTypeMismatch, -1, path, errors.New("unknown value kind"))
	}
	return nil
}

func canonicalInteger(value, path string) (string, error) {
	if strings.ContainsAny(value, ".eE") {
		return "", contractError(InvalidSchema, CodeFloatingPointForbidden, -1, path, errors.New("JSON floating-point values are forbidden"))
	}
	if value == "-0" {
		return "", contractError(InvalidSchema, CodeInvalidNumber, -1, path, errors.New("negative zero integer is forbidden"))
	}
	parsed, err := strconv.ParseInt(value, 10, 64)
	if err != nil {
		return "", contractError(InvalidSchema, CodeUnsafeInteger, -1, path, err)
	}
	if parsed < -MaxSafeInteger || parsed > MaxSafeInteger {
		return "", contractError(InvalidSchema, CodeUnsafeInteger, -1, path, fmt.Errorf("integer is outside interoperable range"))
	}
	return strconv.FormatInt(parsed, 10), nil
}

func appendCanonicalString(out *bytes.Buffer, value string) {
	out.WriteByte('"')
	for _, r := range value {
		switch r {
		case '"':
			out.WriteString(`\"`)
		case '\\':
			out.WriteString(`\\`)
		case '\b':
			out.WriteString(`\b`)
		case '\f':
			out.WriteString(`\f`)
		case '\n':
			out.WriteString(`\n`)
		case '\r':
			out.WriteString(`\r`)
		case '\t':
			out.WriteString(`\t`)
		default:
			if r < 0x20 {
				fmt.Fprintf(out, `\u%04x`, r)
			} else {
				out.WriteRune(r)
			}
		}
	}
	out.WriteByte('"')
}

func sortMembersUTF16(members []Member) {
	encoded := make(map[string][]uint16, len(members))
	for _, member := range members {
		encoded[member.Key] = utf16.Encode([]rune(member.Key))
	}
	sort.Slice(members, func(i, j int) bool {
		left, right := encoded[members[i].Key], encoded[members[j].Key]
		for index := 0; index < len(left) && index < len(right); index++ {
			if left[index] != right[index] {
				return left[index] < right[index]
			}
		}
		return len(left) < len(right)
	})
}

func ValidateHash(value string) error {
	if len(value) != 71 || !strings.HasPrefix(value, HashPrefix) {
		return contractError(InvalidSchema, CodeInvalidHash, -1, "$", errors.New("hash must be sha256 plus 64 lowercase hexadecimal characters"))
	}
	for _, b := range []byte(value[len(HashPrefix):]) {
		if !((b >= '0' && b <= '9') || (b >= 'a' && b <= 'f')) {
			return contractError(InvalidSchema, CodeInvalidHash, -1, "$", errors.New("hash contains non-lowercase-hexadecimal character"))
		}
	}
	if value == HashPrefix+strings.Repeat("0", 64) {
		return contractError(InvalidSchema, CodeInvalidHash, -1, "$", errors.New("all-zero hash is forbidden"))
	}
	return nil
}

func ValidateTimestamp(value string) error {
	if len(value) != len("2000-01-01T00:00:00.000000000Z") || value[4] != '-' || value[7] != '-' || value[10] != 'T' || value[13] != ':' || value[16] != ':' || value[19] != '.' || value[29] != 'Z' {
		return contractError(InvalidSchema, CodeInvalidTimestamp, -1, "$", errors.New("timestamp must have exactly nine fractional digits and UTC Z"))
	}
	parsed, err := time.Parse("2006-01-02T15:04:05.000000000Z", value)
	if err != nil || parsed.Year() == 0 || parsed.UTC().Format("2006-01-02T15:04:05.000000000Z") != value {
		return contractError(InvalidSchema, CodeInvalidTimestamp, -1, "$", fmt.Errorf("invalid canonical timestamp: %w", err))
	}
	return nil
}

func FormatTimestamp(value time.Time) (string, error) {
	value = value.UTC()
	if value.Year() < 1 || value.Year() > 9999 {
		return "", contractError(InvalidSchema, CodeInvalidTimestamp, -1, "$", errors.New("timestamp year is outside 0001..9999"))
	}
	return value.Format("2006-01-02T15:04:05.000000000Z"), nil
}

func FormatTimestampMillis(value int64) (string, error) {
	return FormatTimestamp(time.UnixMilli(value))
}

func ValidateDecimal(value string, scale int) error {
	if scale < 0 || scale > 64 || value == "" || strings.HasPrefix(value, "+") || strings.ContainsAny(value, "eE") {
		return contractError(InvalidSchema, CodeInvalidDecimal, -1, "$", errors.New("invalid decimal form"))
	}
	negative := strings.HasPrefix(value, "-")
	body := strings.TrimPrefix(value, "-")
	parts := strings.Split(body, ".")
	if len(parts) != 2 || len(parts[1]) != scale || parts[0] == "" {
		return contractError(InvalidSchema, CodeInvalidDecimal, -1, "$", fmt.Errorf("decimal must have scale %d", scale))
	}
	if len(parts[0]) > 1 && parts[0][0] == '0' {
		return contractError(InvalidSchema, CodeInvalidDecimal, -1, "$", errors.New("decimal has a leading zero"))
	}
	for _, part := range parts {
		for _, r := range part {
			if r < '0' || r > '9' {
				return contractError(InvalidSchema, CodeInvalidDecimal, -1, "$", errors.New("decimal contains a non-digit"))
			}
		}
	}
	if negative && strings.Trim(parts[0]+parts[1], "0") == "" {
		return contractError(InvalidSchema, CodeInvalidDecimal, -1, "$", errors.New("negative zero is forbidden"))
	}
	return nil
}

func FormatDecimal(value float64, scale int) (string, error) {
	if math.IsNaN(value) || math.IsInf(value, 0) {
		return "", contractError(InvalidSchema, CodeInvalidDecimal, -1, "$", errors.New("decimal source is non-finite"))
	}
	if value == 0 {
		value = 0
	}
	formatted := strconv.FormatFloat(value, 'f', scale, 64)
	if err := ValidateDecimal(formatted, scale); err != nil {
		return "", err
	}
	return formatted, nil
}

func ValidateRelativePath(value string) error {
	if value == "" || strings.HasPrefix(value, "/") || strings.Contains(value, "\\") || strings.ContainsRune(value, 0) || strings.Contains(value, "%2e") || strings.Contains(value, "%2E") {
		return contractError(InvalidSchema, CodeInvalidPath, -1, "$", errors.New("path is empty, absolute, escaped, or encoded"))
	}
	if len(value) >= 2 && ((value[0] >= 'A' && value[0] <= 'Z') || (value[0] >= 'a' && value[0] <= 'z')) && value[1] == ':' {
		return contractError(InvalidSchema, CodeInvalidPath, -1, "$", errors.New("drive-prefixed path is forbidden"))
	}
	for _, part := range strings.Split(value, "/") {
		if part == "" || part == "." || part == ".." {
			return contractError(InvalidSchema, CodeInvalidPath, -1, "$", errors.New("path contains an empty or traversal segment"))
		}
	}
	return nil
}

func HashCanonical(contract string, version int, canonicalization, role string, payload []byte) (string, error) {
	if contract == "" || version <= 0 || canonicalization == "" || role == "" {
		return "", contractError(InvalidSchema, CodeSemanticViolation, -1, "$", errors.New("hash domain fields are incomplete"))
	}
	if !asciiToken(contract) || !asciiToken(canonicalization) || !asciiToken(role) {
		return "", contractError(InvalidSchema, CodeSemanticViolation, -1, "$", errors.New("hash domain fields must be printable ASCII without whitespace"))
	}
	h := sha256.New()
	h.Write([]byte("AK-HASH-V1\x00"))
	writeLengthPrefixed(h, []byte(contract))
	writeLengthPrefixed(h, []byte(strconv.Itoa(version)))
	writeLengthPrefixed(h, []byte(canonicalization))
	writeLengthPrefixed(h, []byte(role))
	var length [8]byte
	binary.BigEndian.PutUint64(length[:], uint64(len(payload)))
	h.Write(length[:])
	h.Write(payload)
	return HashPrefix + hex.EncodeToString(h.Sum(nil)), nil
}

func HashRaw(contract string, version int, role string, payload []byte) (string, error) {
	return HashCanonical(contract, version, CanonicalRawVersion, role, payload)
}

func HashRawReader(contract string, version int, role string, length int64, reader io.Reader) (string, error) {
	if contract == "" || version <= 0 || role == "" || length < 0 || !asciiToken(contract) || !asciiToken(role) {
		return "", contractError(InvalidSchema, CodeSemanticViolation, -1, "$", errors.New("raw hash domain or length is invalid"))
	}
	h := sha256.New()
	h.Write([]byte("AK-HASH-V1\x00"))
	writeLengthPrefixed(h, []byte(contract))
	writeLengthPrefixed(h, []byte(strconv.Itoa(version)))
	writeLengthPrefixed(h, []byte(CanonicalRawVersion))
	writeLengthPrefixed(h, []byte(role))
	var encodedLength [8]byte
	binary.BigEndian.PutUint64(encodedLength[:], uint64(length))
	h.Write(encodedLength[:])
	written, err := io.CopyN(h, reader, length)
	if err != nil {
		return "", contractError(InvalidSchema, CodeRawHashMismatch, -1, "$", err)
	}
	if written != length {
		return "", contractError(InvalidSchema, CodeRawHashMismatch, -1, "$", fmt.Errorf("read %d bytes, expected %d", written, length))
	}
	var trailing [1]byte
	if n, err := reader.Read(trailing[:]); n != 0 || err != io.EOF {
		return "", contractError(InvalidSchema, CodeRawHashMismatch, -1, "$", errors.New("raw source length changed during hashing"))
	}
	return HashPrefix + hex.EncodeToString(h.Sum(nil)), nil
}

func HashValue(contract string, version int, role string, value any) (string, []byte, error) {
	canonical, err := CanonicalizeValue(value)
	if err != nil {
		return "", nil, err
	}
	hash, err := HashCanonical(contract, version, CanonicalJSONVersion, role, canonical)
	return hash, canonical, err
}

func HashArtifactValue(contract string, version int, role, selfHashField string, value any) (string, []byte, error) {
	raw, err := json.Marshal(value)
	if err != nil {
		return "", nil, contractError(InvalidSchema, CodeTypeMismatch, -1, "$", err)
	}
	parsed, err := Parse(raw)
	if err != nil {
		return "", nil, err
	}
	payloadValue, err := parsed.cloneWithoutTopLevelMember(selfHashField)
	if err != nil {
		return "", nil, err
	}
	payload, err := payloadValue.CanonicalBytes()
	if err != nil {
		return "", nil, err
	}
	hash, err := HashCanonical(contract, version, CanonicalJSONVersion, role, payload)
	return hash, payload, err
}

func HashArtifactBytes(data []byte, contract string, version int, role, selfHashField string) (string, []byte, error) {
	parsed, err := Parse(data)
	if err != nil {
		return "", nil, err
	}
	payloadValue, err := parsed.cloneWithoutTopLevelMember(selfHashField)
	if err != nil {
		return "", nil, err
	}
	payload, err := payloadValue.CanonicalBytes()
	if err != nil {
		return "", nil, err
	}
	hash, err := HashCanonical(contract, version, CanonicalJSONVersion, role, payload)
	return hash, payload, err
}

func EqualHash(left, right string) bool {
	if ValidateHash(left) != nil || ValidateHash(right) != nil {
		return false
	}
	leftBytes, _ := hex.DecodeString(left[len(HashPrefix):])
	rightBytes, _ := hex.DecodeString(right[len(HashPrefix):])
	return subtle.ConstantTimeCompare(leftBytes, rightBytes) == 1
}

func writeLengthPrefixed(writer interface{ Write([]byte) (int, error) }, value []byte) {
	var length [4]byte
	binary.BigEndian.PutUint32(length[:], uint32(len(value)))
	writer.Write(length[:])
	writer.Write(value)
}

func asciiToken(value string) bool {
	for _, r := range value {
		if r < 0x21 || r > 0x7e {
			return false
		}
	}
	return true
}
