// Code generated by ak-ops/contracts/canonical/v1/generator; DO NOT EDIT.
// Source schema set: sha256:659fe8c948d522801ddf7082d4dd19e6203e8293b0c02b4d44005f98ca874c62

package canonicalcontract

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

type conformanceVector struct {
	ID                    string `json:"vector_id"`
	Description           string `json:"description"`
	Operation             string `json:"operation"`
	ContractName          string `json:"contract_name"`
	ContractVersion       int    `json:"contract_version"`
	ArtifactRole          string `json:"artifact_role"`
	RequireCanonicalInput bool   `json:"require_canonical_input"`
	InputBase64           string `json:"input_base64"`
	ReferenceHash         string `json:"reference_hash"`
	ExpectedResult        string `json:"expected_result"`
	ExpectedErrorCode     string `json:"expected_error_code"`
	ExpectedCanonicalB64  string `json:"expected_canonical_base64"`
	ExpectedArtifactHash  string `json:"expected_artifact_hash"`
	ExpectedSemanticValid bool   `json:"expected_semantic_valid"`
}

type conformanceCorpus struct {
	CorpusSchema     string              `json:"corpus_schema"`
	CorpusVersion    int                 `json:"corpus_version"`
	Canonicalization string              `json:"canonicalization"`
	SchemaSetHash    string              `json:"schema_set_hash"`
	Vectors          []conformanceVector `json:"vectors"`
}

type conformanceManifest struct {
	CorpusSHA256  string `json:"corpus_sha256"`
	SchemaSetHash string `json:"schema_set_hash"`
	VectorCount   int    `json:"vector_count"`
}

func TestSharedCanonicalConformanceCorpus(t *testing.T) {
	corpusBytes, err := os.ReadFile("testdata/canonical/v1/corpus.json")
	if err != nil {
		t.Fatal(err)
	}
	manifestBytes, err := os.ReadFile("testdata/canonical/v1/manifest.json")
	if err != nil {
		t.Fatal(err)
	}
	var manifest conformanceManifest
	if err := json.Unmarshal(manifestBytes, &manifest); err != nil {
		t.Fatal(err)
	}
	digest := sha256.Sum256(corpusBytes)
	actualCorpusHash := HashPrefix + hex.EncodeToString(digest[:])
	if manifest.CorpusSHA256 != actualCorpusHash || manifest.SchemaSetHash != SchemaSetHash {
		t.Fatalf("corpus manifest mismatch: hash=%s schema=%s", actualCorpusHash, SchemaSetHash)
	}
	var corpus conformanceCorpus
	if err := json.Unmarshal(corpusBytes, &corpus); err != nil {
		t.Fatal(err)
	}
	if corpus.CorpusSchema != "ak.contract.conformance.corpus.v1" || corpus.CorpusVersion != 1 || corpus.Canonicalization != CanonicalJSONVersion || corpus.SchemaSetHash != SchemaSetHash || manifest.VectorCount != len(corpus.Vectors) {
		t.Fatalf("unsupported corpus header: %#v", corpus)
	}
	for _, vector := range corpus.Vectors {
		vector := vector
		t.Run(vector.ID, func(t *testing.T) {
			input, err := base64.StdEncoding.DecodeString(vector.InputBase64)
			if err != nil {
				t.Fatal(err)
			}
			result, code, validated := executeConformanceVector(vector, input)
			if string(result) != vector.ExpectedResult || string(code) != vector.ExpectedErrorCode {
				t.Fatalf("got %s/%s, want %s/%s", result, code, vector.ExpectedResult, vector.ExpectedErrorCode)
			}
			if result != ValidContract {
				if vector.ExpectedSemanticValid {
					t.Fatal("invalid vector claims semantic validity")
				}
				return
			}
			expectedCanonical, err := base64.StdEncoding.DecodeString(vector.ExpectedCanonicalB64)
			if err != nil {
				t.Fatal(err)
			}
			if validated == nil || !bytes.Equal(validated.CanonicalBytes, expectedCanonical) || validated.DeclaredHash != vector.ExpectedArtifactHash {
				t.Fatalf("canonical bytes or hash mismatch")
			}
			reparsed, err := ValidateArtifact(expectedCanonical, true)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(reparsed.CanonicalBytes, expectedCanonical) || reparsed.DeclaredHash != vector.ExpectedArtifactHash || reparsed.RecomputedHash != vector.ExpectedArtifactHash {
				t.Fatal("reparse/reserialize/hash is not idempotent")
			}
		})
	}
}

func executeConformanceVector(vector conformanceVector, input []byte) (ResultCode, ErrorCode, *ValidationResult) {
	switch vector.Operation {
	case "artifact":
		result, err := ValidateArtifact(input, vector.RequireCanonicalInput)
		resultCode, errorCode := Classify(err)
		return resultCode, errorCode, &result
	case "raw_hash_compare":
		actual, err := HashRaw(vector.ContractName, vector.ContractVersion, vector.ArtifactRole, input)
		if err != nil {
			result, code := Classify(err)
			return result, code, nil
		}
		if !EqualHash(actual, vector.ReferenceHash) {
			return HashMismatch, CodeRawHashMismatch, nil
		}
		return ValidContract, CodeNone, nil
	case "artifact_reference_compare":
		result, err := ValidateArtifact(input, true)
		if err != nil {
			resultCode, code := Classify(err)
			return resultCode, code, &result
		}
		if !EqualHash(result.DeclaredHash, vector.ReferenceHash) {
			return CrossReferenceMismatch, CodeReferenceHashMismatch, &result
		}
		return ValidContract, CodeNone, &result
	default:
		return InvalidSchema, CodeSemanticViolation, nil
	}
}
