// Code generated by ak-ops/contracts/canonical/v1/generator; DO NOT EDIT.
// Source schema set: sha256:659fe8c948d522801ddf7082d4dd19e6203e8293b0c02b4d44005f98ca874c62

package canonicalcontract

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
)

type schemaRegistration struct {
	SchemaName       string `json:"schema_name"`
	SchemaVersion    int    `json:"schema_version"`
	ArtifactRole     string `json:"artifact_role"`
	Owner            string `json:"owner"`
	SchemaFile       string `json:"schema_file"`
	SchemaPointer    string `json:"schema_pointer"`
	SelfHashField    string `json:"self_hash_field"`
	MaxDocumentBytes int    `json:"max_document_bytes"`
}

type sourceRegistry struct {
	Canonicalization string               `json:"canonicalization"`
	HashAlgorithm    string               `json:"hash_algorithm"`
	RegistrySchema   string               `json:"registry_schema"`
	ResourceLimits   Limits               `json:"-"`
	Schemas          []schemaRegistration `json:"schemas"`
}

type rawRegistry struct {
	Canonicalization string `json:"canonicalization"`
	HashAlgorithm    string `json:"hash_algorithm"`
	RegistrySchema   string `json:"registry_schema"`
	ResourceLimits   struct {
		MaxArrayLength   int `json:"max_array_length"`
		MaxDocumentBytes int `json:"max_document_bytes"`
		MaxFieldCount    int `json:"max_field_count"`
		MaxNestingDepth  int `json:"max_nesting_depth"`
		MaxStringBytes   int `json:"max_string_bytes"`
	} `json:"resource_limits"`
	Schemas []schemaRegistration `json:"schemas"`
}

type ContractHeader struct {
	SchemaName       string `json:"schema_name"`
	SchemaVersion    int    `json:"schema_version"`
	Canonicalization string `json:"canonicalization"`
	HashAlgorithm    string `json:"hash_algorithm"`
	ArtifactRole     string `json:"artifact_role"`
}

func NewHeader(schemaName string, schemaVersion int, artifactRole string) ContractHeader {
	return ContractHeader{
		SchemaName:       schemaName,
		SchemaVersion:    schemaVersion,
		Canonicalization: CanonicalJSONVersion,
		HashAlgorithm:    HashAlgorithm,
		ArtifactRole:     artifactRole,
	}
}

type ValidationResult struct {
	ResultCode     ResultCode
	ErrorCode      ErrorCode
	SchemaName     string
	SchemaVersion  int
	ArtifactRole   string
	CanonicalBytes []byte
	DeclaredHash   string
	RecomputedHash string
}

var (
	registryOnce      sync.Once
	loadedRegistry    sourceRegistry
	loadedSchemas     map[string]any
	registryLoadError error
)

func loadRegistry() (sourceRegistry, map[string]any, error) {
	registryOnce.Do(func() {
		var raw rawRegistry
		if err := json.Unmarshal([]byte(embeddedContractSources["registry.json"]), &raw); err != nil {
			registryLoadError = fmt.Errorf("decode embedded registry: %w", err)
			return
		}
		loadedRegistry = sourceRegistry{
			Canonicalization: raw.Canonicalization,
			HashAlgorithm:    raw.HashAlgorithm,
			RegistrySchema:   raw.RegistrySchema,
			Schemas:          raw.Schemas,
			ResourceLimits: Limits{
				MaxArrayLength:   raw.ResourceLimits.MaxArrayLength,
				MaxDocumentBytes: raw.ResourceLimits.MaxDocumentBytes,
				MaxFieldCount:    raw.ResourceLimits.MaxFieldCount,
				MaxNestingDepth:  raw.ResourceLimits.MaxNestingDepth,
				MaxStringBytes:   raw.ResourceLimits.MaxStringBytes,
			},
		}
		if loadedRegistry.Canonicalization != CanonicalJSONVersion || loadedRegistry.HashAlgorithm != HashAlgorithm || loadedRegistry.RegistrySchema != "ak.contract.registry.v1" {
			registryLoadError = errors.New("embedded registry profile mismatch")
			return
		}
		loadedSchemas = map[string]any{}
		for name, source := range embeddedContractSources {
			if !strings.HasPrefix(name, "schemas/") {
				continue
			}
			decoder := json.NewDecoder(strings.NewReader(source))
			decoder.UseNumber()
			var document any
			if err := decoder.Decode(&document); err != nil {
				registryLoadError = fmt.Errorf("decode embedded %s: %w", name, err)
				return
			}
			loadedSchemas[name] = document
		}
		seen := map[string]struct{}{}
		for _, registration := range loadedRegistry.Schemas {
			key := fmt.Sprintf("%s@%d", registration.SchemaName, registration.SchemaVersion)
			if registration.SchemaName == "" || registration.SchemaVersion <= 0 || registration.ArtifactRole == "" || registration.Owner == "" || registration.SchemaFile == "" || registration.SchemaPointer == "" || registration.SelfHashField != "artifact_hash" {
				registryLoadError = fmt.Errorf("incomplete schema registration %s", key)
				return
			}
			if _, exists := seen[key]; exists {
				registryLoadError = fmt.Errorf("duplicate schema registration %s", key)
				return
			}
			seen[key] = struct{}{}
			if _, exists := loadedSchemas[registration.SchemaFile]; !exists {
				registryLoadError = fmt.Errorf("schema file %s is not embedded", registration.SchemaFile)
				return
			}
		}
	})
	return loadedRegistry, loadedSchemas, registryLoadError
}

func RegisteredSchemas() ([]ContractHeader, error) {
	registry, _, err := loadRegistry()
	if err != nil {
		return nil, err
	}
	result := make([]ContractHeader, 0, len(registry.Schemas))
	for _, registration := range registry.Schemas {
		result = append(result, NewHeader(registration.SchemaName, registration.SchemaVersion, registration.ArtifactRole))
	}
	sort.Slice(result, func(i, j int) bool {
		if result[i].SchemaName != result[j].SchemaName {
			return result[i].SchemaName < result[j].SchemaName
		}
		return result[i].SchemaVersion < result[j].SchemaVersion
	})
	return result, nil
}

func ValidateArtifact(data []byte, requireCanonical bool) (ValidationResult, error) {
	registry, _, err := loadRegistry()
	if err != nil {
		return ValidationResult{}, contractError(InvalidSchema, CodeSemanticViolation, -1, "$", err)
	}
	limits := registry.ResourceLimits
	value, err := ParseWithLimits(data, limits)
	if err != nil {
		result, code := Classify(err)
		return ValidationResult{ResultCode: result, ErrorCode: code}, err
	}
	result, err := validateParsedArtifact(value, requireCanonical, data, true)
	if err != nil {
		result.ResultCode, result.ErrorCode = Classify(err)
		return result, err
	}
	result.ResultCode = ValidContract
	result.ErrorCode = CodeNone
	return result, nil
}

func validateParsedArtifact(value *Value, requireCanonical bool, original []byte, recurse bool) (ValidationResult, error) {
	header, declaredHash, err := extractHeader(value)
	result := ValidationResult{
		SchemaName:    header.SchemaName,
		SchemaVersion: header.SchemaVersion,
		ArtifactRole:  header.ArtifactRole,
		DeclaredHash:  declaredHash,
	}
	if err != nil {
		return result, err
	}
	registration, err := findRegistration(header.SchemaName, header.SchemaVersion)
	if err != nil {
		return result, err
	}
	if header.Canonicalization != CanonicalJSONVersion {
		return result, contractError(UnsupportedVersion, CodeCanonicalVersionMismatch, -1, "$.contract.canonicalization", fmt.Errorf("got %q", header.Canonicalization))
	}
	if header.HashAlgorithm != HashAlgorithm {
		return result, contractError(UnsupportedVersion, CodeHashAlgorithmMismatch, -1, "$.contract.hash_algorithm", fmt.Errorf("got %q", header.HashAlgorithm))
	}
	if header.ArtifactRole != registration.ArtifactRole {
		return result, contractError(InvalidSchema, CodeArtifactRoleMismatch, -1, "$.contract.artifact_role", fmt.Errorf("expected %q", registration.ArtifactRole))
	}
	if err := ValidateHash(declaredHash); err != nil {
		return result, withPath(err, "$.artifact_hash")
	}
	schema, err := resolveRegisteredSchema(registration)
	if err != nil {
		return result, contractError(InvalidSchema, CodeSemanticViolation, -1, "$", err)
	}
	if err := rejectNullRecursively(value, "$", header.SchemaName); err != nil {
		return result, err
	}
	if err := validateAgainstSchema(value, schema, "$", registration.SchemaFile); err != nil {
		return result, err
	}
	if err := validateSemanticRules(header.SchemaName, value); err != nil {
		return result, err
	}
	canonical, err := value.CanonicalBytes()
	if err != nil {
		return result, err
	}
	result.CanonicalBytes = canonical
	if requireCanonical && !bytes.Equal(original, canonical) {
		return result, contractError(InvalidCanonicalForm, CodeNonCanonicalBytes, -1, "$", errors.New("artifact bytes differ from canonical bytes"))
	}
	recomputed, _, err := HashArtifactBytes(canonical, header.SchemaName, header.SchemaVersion, header.ArtifactRole, registration.SelfHashField)
	if err != nil {
		return result, err
	}
	result.RecomputedHash = recomputed
	if !EqualHash(declaredHash, recomputed) {
		return result, contractError(HashMismatch, CodeSelfHashMismatch, -1, "$.artifact_hash", fmt.Errorf("declared %s recomputed %s", declaredHash, recomputed))
	}
	if recurse {
		if err := validateNestedArtifacts(value, true); err != nil {
			return result, err
		}
	}
	return result, nil
}

func validateNestedArtifacts(value *Value, root bool) error {
	if value == nil {
		return nil
	}
	switch value.Kind {
	case KindObject:
		if !root {
			if _, hasContract := value.Member("contract"); hasContract {
				if _, hasHash := value.Member("artifact_hash"); hasHash {
					if _, err := validateParsedArtifact(value, false, nil, false); err != nil {
						return err
					}
				}
			}
		}
		for _, member := range value.Object {
			if err := validateNestedArtifacts(member.Value, false); err != nil {
				return err
			}
		}
	case KindArray:
		for _, item := range value.Array {
			if err := validateNestedArtifacts(item, false); err != nil {
				return err
			}
		}
	}
	return nil
}

func extractHeader(value *Value) (ContractHeader, string, error) {
	if value == nil || value.Kind != KindObject {
		return ContractHeader{}, "", contractError(InvalidSchema, CodeTypeMismatch, -1, "$", errors.New("artifact root must be an object"))
	}
	contractValue, ok := value.Member("contract")
	if !ok {
		return ContractHeader{}, "", contractError(InvalidSchema, CodeMissingRequiredField, -1, "$.contract", errors.New("contract header is required"))
	}
	if contractValue.Kind != KindObject {
		return ContractHeader{}, "", contractError(InvalidSchema, CodeTypeMismatch, -1, "$.contract", errors.New("contract header must be an object"))
	}
	readString := func(name string) (string, error) {
		field, ok := contractValue.Member(name)
		if !ok {
			return "", contractError(InvalidSchema, CodeMissingRequiredField, -1, "$.contract."+name, errors.New("required header field is missing"))
		}
		if field.Kind != KindString || field.String == "" {
			return "", contractError(InvalidSchema, CodeTypeMismatch, -1, "$.contract."+name, errors.New("header field must be a nonempty string"))
		}
		return field.String, nil
	}
	schemaName, err := readString("schema_name")
	if err != nil {
		return ContractHeader{}, "", err
	}
	schemaVersionValue, ok := contractValue.Member("schema_version")
	if !ok {
		return ContractHeader{}, "", contractError(InvalidSchema, CodeMissingRequiredField, -1, "$.contract.schema_version", errors.New("schema version is required"))
	}
	if schemaVersionValue.Kind != KindNumber || strings.ContainsAny(schemaVersionValue.Number, ".eE-") {
		return ContractHeader{}, "", contractError(InvalidSchema, CodeTypeMismatch, -1, "$.contract.schema_version", errors.New("schema version must be a positive integer"))
	}
	schemaVersion, err := strconv.Atoi(schemaVersionValue.Number)
	if err != nil || schemaVersion <= 0 {
		return ContractHeader{}, "", contractError(InvalidSchema, CodeInvalidRange, -1, "$.contract.schema_version", errors.New("invalid schema version"))
	}
	canonicalization, err := readString("canonicalization")
	if err != nil {
		return ContractHeader{}, "", err
	}
	hashAlgorithm, err := readString("hash_algorithm")
	if err != nil {
		return ContractHeader{}, "", err
	}
	artifactRole, err := readString("artifact_role")
	if err != nil {
		return ContractHeader{}, "", err
	}
	hashValue, ok := value.Member("artifact_hash")
	if !ok {
		return ContractHeader{}, "", contractError(InvalidSchema, CodeMissingRequiredField, -1, "$.artifact_hash", errors.New("artifact hash is required"))
	}
	if hashValue.Kind != KindString {
		return ContractHeader{}, "", contractError(InvalidSchema, CodeTypeMismatch, -1, "$.artifact_hash", errors.New("artifact hash must be a string"))
	}
	return ContractHeader{
		SchemaName:       schemaName,
		SchemaVersion:    schemaVersion,
		Canonicalization: canonicalization,
		HashAlgorithm:    hashAlgorithm,
		ArtifactRole:     artifactRole,
	}, hashValue.String, nil
}

func findRegistration(schemaName string, schemaVersion int) (schemaRegistration, error) {
	registry, _, err := loadRegistry()
	if err != nil {
		return schemaRegistration{}, err
	}
	nameKnown := false
	for _, registration := range registry.Schemas {
		if registration.SchemaName == schemaName {
			nameKnown = true
			if registration.SchemaVersion == schemaVersion {
				return registration, nil
			}
		}
	}
	if nameKnown {
		return schemaRegistration{}, contractError(UnsupportedVersion, CodeSchemaVersionMismatch, -1, "$.contract.schema_version", fmt.Errorf("unsupported version %d", schemaVersion))
	}
	return schemaRegistration{}, contractError(UnsupportedVersion, CodeUnknownContract, -1, "$.contract.schema_name", fmt.Errorf("unknown contract %q", schemaName))
}

func resolveRegisteredSchema(registration schemaRegistration) (any, error) {
	_, documents, err := loadRegistry()
	if err != nil {
		return nil, err
	}
	document, ok := documents[registration.SchemaFile]
	if !ok {
		return nil, fmt.Errorf("schema document %s is missing", registration.SchemaFile)
	}
	return resolvePointer(document, registration.SchemaPointer)
}

func resolvePointer(document any, pointer string) (any, error) {
	if pointer == "#" || pointer == "" {
		return document, nil
	}
	if !strings.HasPrefix(pointer, "#/") {
		return nil, fmt.Errorf("unsupported JSON pointer %q", pointer)
	}
	current := document
	for _, raw := range strings.Split(strings.TrimPrefix(pointer, "#/"), "/") {
		segment := strings.ReplaceAll(strings.ReplaceAll(raw, "~1", "/"), "~0", "~")
		object, ok := current.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("pointer segment %q is not an object", segment)
		}
		current, ok = object[segment]
		if !ok {
			return nil, fmt.Errorf("pointer segment %q does not exist", segment)
		}
	}
	return current, nil
}

func validateAgainstSchema(value *Value, schema any, path, baseFile string) error {
	object, ok := schema.(map[string]any)
	if !ok {
		return contractError(InvalidSchema, CodeSemanticViolation, -1, path, errors.New("schema node is not an object"))
	}
	if reference, ok := object["$ref"].(string); ok {
		resolved, resolvedBase, err := resolveReference(reference, baseFile)
		if err != nil {
			return contractError(InvalidSchema, CodeSemanticViolation, -1, path, err)
		}
		return validateAgainstSchema(value, resolved, path, resolvedBase)
	}
	if allOf, ok := object["allOf"].([]any); ok {
		for _, child := range allOf {
			if err := validateAgainstSchema(value, child, path, baseFile); err != nil {
				return err
			}
		}
	}
	if oneOf, ok := object["oneOf"].([]any); ok {
		matches := 0
		for _, child := range oneOf {
			if validateAgainstSchema(value, child, path, baseFile) == nil {
				matches++
			}
		}
		if matches != 1 {
			return contractError(InvalidSchema, CodeTypeMismatch, -1, path, fmt.Errorf("oneOf matched %d branches", matches))
		}
	}
	if expectedType, ok := object["type"].(string); ok {
		if err := validateType(value, expectedType, path); err != nil {
			return err
		}
	}
	if constant, exists := object["const"]; exists && !schemaScalarEqual(value, constant) {
		return contractError(InvalidSchema, CodeInvalidConstant, -1, path, errors.New("value differs from schema constant"))
	}
	if enum, ok := object["enum"].([]any); ok {
		matched := false
		for _, allowed := range enum {
			if schemaScalarEqual(value, allowed) {
				matched = true
				break
			}
		}
		if !matched {
			return contractError(InvalidSchema, CodeInvalidEnum, -1, path, errors.New("value is not in closed enum"))
		}
	}
	switch value.Kind {
	case KindObject:
		if err := validateObjectSchema(value, object, path, baseFile); err != nil {
			return err
		}
	case KindArray:
		if err := validateArraySchema(value, object, path, baseFile); err != nil {
			return err
		}
	case KindString:
		if err := validateStringSchema(value.String, object, path); err != nil {
			return err
		}
	case KindNumber:
		if err := validateNumberSchema(value.Number, object, path); err != nil {
			return err
		}
	}
	return nil
}

func resolveReference(reference, baseFile string) (any, string, error) {
	fileName, pointer, found := strings.Cut(reference, "#")
	if !found {
		pointer = ""
	}
	if fileName == "" {
		fileName = baseFile
	} else if !strings.HasPrefix(fileName, "schemas/") {
		fileName = "schemas/" + fileName
	}
	_, documents, err := loadRegistry()
	if err != nil {
		return nil, "", err
	}
	document, ok := documents[fileName]
	if !ok {
		return nil, "", fmt.Errorf("referenced schema %s is missing", fileName)
	}
	resolved, err := resolvePointer(document, "#"+pointer)
	return resolved, fileName, err
}

func validateType(value *Value, expected, path string) error {
	matched := expected == "object" && value.Kind == KindObject ||
		expected == "array" && value.Kind == KindArray ||
		expected == "string" && value.Kind == KindString ||
		expected == "integer" && value.Kind == KindNumber && !strings.ContainsAny(value.Number, ".eE") ||
		expected == "boolean" && value.Kind == KindBoolean ||
		expected == "null" && value.Kind == KindNull
	if !matched {
		return contractError(InvalidSchema, CodeTypeMismatch, -1, path, fmt.Errorf("expected %s", expected))
	}
	if value.Kind == KindNull {
		return contractError(InvalidSchema, CodeProhibitedNull, -1, path, errors.New("null is forbidden"))
	}
	return nil
}

func validateObjectSchema(value *Value, schema map[string]any, path, baseFile string) error {
	properties, _ := schema["properties"].(map[string]any)
	requiredSet := map[string]struct{}{}
	if required, ok := schema["required"].([]any); ok {
		for _, item := range required {
			name, ok := item.(string)
			if ok {
				requiredSet[name] = struct{}{}
			}
		}
	}
	for required := range requiredSet {
		if _, exists := value.Member(required); !exists {
			return contractError(InvalidSchema, CodeMissingRequiredField, -1, path+"."+required, errors.New("required field is missing"))
		}
	}
	additionalAllowed := true
	if additional, ok := schema["additionalProperties"].(bool); ok {
		additionalAllowed = additional
	}
	for _, member := range value.Object {
		propertySchema, exists := properties[member.Key]
		if !exists {
			if !additionalAllowed {
				return contractError(InvalidSchema, CodeUnknownField, -1, path+"."+member.Key, errors.New("unknown field"))
			}
			continue
		}
		if err := validateAgainstSchema(member.Value, propertySchema, path+"."+member.Key, baseFile); err != nil {
			return err
		}
	}
	return nil
}

func validateArraySchema(value *Value, schema map[string]any, path, baseFile string) error {
	if minimum, ok := schemaInteger(schema["minItems"]); ok && int64(len(value.Array)) < minimum {
		return contractError(InvalidSchema, CodeInvalidLength, -1, path, fmt.Errorf("array has fewer than %d items", minimum))
	}
	if maximum, ok := schemaInteger(schema["maxItems"]); ok && int64(len(value.Array)) > maximum {
		return contractError(ResourceLimitExceeded, CodeArrayTooLong, -1, path, fmt.Errorf("array has more than %d items", maximum))
	}
	if items, exists := schema["items"]; exists {
		for index, item := range value.Array {
			if err := validateAgainstSchema(item, items, fmt.Sprintf("%s[%d]", path, index), baseFile); err != nil {
				return err
			}
		}
	}
	if unique, _ := schema["uniqueItems"].(bool); unique {
		seen := map[string]struct{}{}
		for index, item := range value.Array {
			canonical, err := item.CanonicalBytes()
			if err != nil {
				return err
			}
			key := string(canonical)
			if _, exists := seen[key]; exists {
				return contractError(InvalidSchema, CodeDuplicateSetMember, -1, fmt.Sprintf("%s[%d]", path, index), errors.New("duplicate array member"))
			}
			seen[key] = struct{}{}
		}
	}
	if sortedScalar, _ := schema["x-ak-sorted"].(bool); sortedScalar {
		for index := 1; index < len(value.Array); index++ {
			left, right := value.Array[index-1], value.Array[index]
			if left.Kind != KindString || right.Kind != KindString || left.String >= right.String {
				code := CodeNonCanonicalSetOrder
				if left.Kind == KindString && right.Kind == KindString && left.String == right.String {
					code = CodeDuplicateSetMember
				}
				return contractError(InvalidCanonicalForm, code, -1, fmt.Sprintf("%s[%d]", path, index), errors.New("set array is not strictly sorted"))
			}
		}
	}
	if orderKey, ok := schema["x-ak-order-key"].(string); ok {
		previous := ""
		for index, item := range value.Array {
			field, exists := item.Member(orderKey)
			if !exists || field.Kind != KindString {
				return contractError(InvalidSchema, CodeTypeMismatch, -1, fmt.Sprintf("%s[%d].%s", path, index, orderKey), errors.New("order key must be a string"))
			}
			if index > 0 && previous >= field.String {
				code := CodeNonCanonicalSetOrder
				if previous == field.String {
					code = CodeDuplicateSetMember
				}
				return contractError(InvalidCanonicalForm, code, -1, fmt.Sprintf("%s[%d].%s", path, index, orderKey), errors.New("object array is not strictly sorted"))
			}
			previous = field.String
		}
	}
	return nil
}

func validateStringSchema(value string, schema map[string]any, path string) error {
	if format, ok := schema["x-ak-format"].(string); ok {
		var err error
		switch {
		case format == "hash":
			err = ValidateHash(value)
		case format == "timestamp":
			err = ValidateTimestamp(value)
		case format == "path":
			err = ValidateRelativePath(value)
		case strings.HasPrefix(format, "decimal-"):
			scale, parseErr := strconv.Atoi(strings.TrimPrefix(format, "decimal-"))
			if parseErr != nil {
				err = parseErr
			} else {
				err = ValidateDecimal(value, scale)
			}
		}
		if err != nil {
			return withPath(err, path)
		}
	}
	if maximum, ok := schemaInteger(schema["maxLength"]); ok && int64(len([]rune(value))) > maximum {
		return contractError(InvalidSchema, CodeInvalidLength, -1, path, errors.New("string is too long"))
	}
	if minimum, ok := schemaInteger(schema["minLength"]); ok && int64(len([]rune(value))) < minimum {
		return contractError(InvalidSchema, CodeInvalidLength, -1, path, errors.New("string is too short"))
	}
	if pattern, ok := schema["pattern"].(string); ok {
		matched, err := regexp.MatchString(pattern, value)
		if err != nil {
			return contractError(InvalidSchema, CodeSemanticViolation, -1, path, err)
		}
		if !matched {
			return contractError(InvalidSchema, CodeInvalidPattern, -1, path, fmt.Errorf("value does not match %s", pattern))
		}
	}
	return nil
}

func validateNumberSchema(value string, schema map[string]any, path string) error {
	canonical, err := canonicalInteger(value, path)
	if err != nil {
		return err
	}
	parsed, _ := strconv.ParseInt(canonical, 10, 64)
	if minimum, ok := schemaInteger(schema["minimum"]); ok && parsed < minimum {
		return contractError(InvalidSchema, CodeInvalidRange, -1, path, fmt.Errorf("integer is below %d", minimum))
	}
	if maximum, ok := schemaInteger(schema["maximum"]); ok && parsed > maximum {
		return contractError(InvalidSchema, CodeInvalidRange, -1, path, fmt.Errorf("integer is above %d", maximum))
	}
	return nil
}

func schemaInteger(value any) (int64, bool) {
	switch typed := value.(type) {
	case json.Number:
		parsed, err := typed.Int64()
		return parsed, err == nil
	case float64:
		return int64(typed), typed == float64(int64(typed))
	case int64:
		return typed, true
	default:
		return 0, false
	}
}

func schemaScalarEqual(value *Value, expected any) bool {
	switch typed := expected.(type) {
	case string:
		return value.Kind == KindString && value.String == typed
	case bool:
		return value.Kind == KindBoolean && value.Bool == typed
	case nil:
		return value.Kind == KindNull
	case json.Number:
		return value.Kind == KindNumber && value.Number == typed.String()
	case float64:
		return value.Kind == KindNumber && value.Number == strconv.FormatFloat(typed, 'f', -1, 64)
	default:
		return false
	}
}

func validateSemanticRules(schemaName string, value *Value) error {
	switch schemaName {
	case "ak.historian.research_identity_manifest":
		return validateHistorianManifestReferences(value)
	case "ak.engine.bound_research_identity":
		return validateBoundIdentityReferences(value)
	case "ak.engine.evaluation_series_identity":
		return requireStrictlyIncreasingStringArray(value, "timestamps", "$.timestamps")
	case "ak.engine.consumed_input_identity":
		return requireStrictlyIncreasingStringArray(value, "evaluation_event_timestamps", "$.evaluation_event_timestamps")
	case "ak.engine.research_evidence":
		return validateResearchEvidenceReferences(value)
	case "ak.engine.research_diagnostic":
		return validateResearchDiagnosticReferences(value)
	default:
		return nil
	}
}

func rejectNullRecursively(value *Value, path, schemaName string) error {
	switch value.Kind {
	case KindNull:
		return contractError(InvalidSchema, CodeProhibitedNull, -1, path, fmt.Errorf("null is forbidden by %s", schemaName))
	case KindObject:
		for _, member := range value.Object {
			if err := rejectNullRecursively(member.Value, path+"."+member.Key, schemaName); err != nil {
				return err
			}
		}
	case KindArray:
		for index, item := range value.Array {
			if err := rejectNullRecursively(item, fmt.Sprintf("%s[%d]", path, index), schemaName); err != nil {
				return err
			}
		}
	}
	return nil
}

func validateHistorianManifestReferences(value *Value) error {
	dataset, ok := value.Member("dataset")
	if !ok {
		return nil
	}
	pit, ok := value.Member("pit_evidence")
	if !ok {
		return nil
	}
	for _, field := range []string{"dataset_id", "dataset_version"} {
		if err := requireEqualString(dataset, pit, field, "$.dataset", "$.pit_evidence"); err != nil {
			return err
		}
	}
	if err := requireReferenceHash(dataset, "artifact_hash", pit, "dataset_hash", "$.dataset", "$.pit_evidence"); err != nil {
		return err
	}
	for _, pair := range []struct {
		member string
		field  string
	}{
		{"source_archive", "source_archive_hash"},
		{"availability_policy", "availability_policy_hash"},
		{"coverage_policy", "coverage_policy_hash"},
	} {
		referenced, ok := value.Member(pair.member)
		if !ok {
			continue
		}
		if err := requireReferenceHash(referenced, "artifact_hash", pit, pair.field, "$."+pair.member, "$.pit_evidence"); err != nil {
			return err
		}
	}
	if err := requireEqualNamedString(value, "dataset_start_utc", dataset, "dataset_start_utc", "$", "$.dataset"); err != nil {
		return err
	}
	if err := requireEqualNamedString(value, "dataset_end_utc", dataset, "dataset_end_utc", "$", "$.dataset"); err != nil {
		return err
	}
	if err := requireEqualNamedString(value, "point_in_time_cutoff_utc", pit, "evaluation_cutoff_utc", "$", "$.pit_evidence"); err != nil {
		return err
	}
	coverage, ok := value.Member("coverage_evidence")
	if ok {
		for _, field := range []string{"requested_start_utc", "requested_end_utc"} {
			manifestField := map[string]string{"requested_start_utc": "dataset_start_utc", "requested_end_utc": "dataset_end_utc"}[field]
			if err := requireEqualNamedString(value, manifestField, coverage, field, "$", "$.coverage_evidence"); err != nil {
				return err
			}
		}
	}
	return nil
}

func validateBoundIdentityReferences(value *Value) error {
	dataset, hasDataset := value.Member("dataset")
	feature, hasFeature := value.Member("feature")
	consumed, hasConsumed := value.Member("consumed_input")
	if hasDataset && hasFeature {
		if err := requireReferenceHash(dataset, "artifact_hash", feature, "input_dataset_hash", "$.dataset", "$.feature"); err != nil {
			return err
		}
	}
	if hasDataset && hasConsumed {
		if err := requireReferenceHash(dataset, "artifact_hash", consumed, "dataset_hash", "$.dataset", "$.consumed_input"); err != nil {
			return err
		}
	}
	pit, hasPIT := value.Member("pit_evidence")
	if hasDataset && hasPIT {
		for _, field := range []string{"dataset_id", "dataset_version"} {
			if err := requireEqualString(dataset, pit, field, "$.dataset", "$.pit_evidence"); err != nil {
				return err
			}
		}
		if err := requireReferenceHash(dataset, "artifact_hash", pit, "dataset_hash", "$.dataset", "$.pit_evidence"); err != nil {
			return err
		}
	}
	if hasFeature && hasConsumed {
		if err := requireReferenceHash(feature, "output_artifact_hash", consumed, "feature_artifact_hash", "$.feature", "$.consumed_input"); err != nil {
			return err
		}
	}
	regime, hasRegime := value.Member("regime")
	if hasRegime && hasFeature {
		if err := requireReferenceHash(feature, "output_artifact_hash", regime, "input_feature_hash", "$.feature", "$.regime"); err != nil {
			return err
		}
	}
	if hasRegime && hasConsumed {
		if err := requireReferenceHash(regime, "output_artifact_hash", consumed, "regime_artifact_hash", "$.regime", "$.consumed_input"); err != nil {
			return err
		}
	}
	series, hasSeries := value.Member("evaluation_series")
	if hasSeries && hasConsumed {
		if err := requireArrayLengthMatchesNumber(consumed, "evaluation_event_timestamps", series, "observation_count", "$.consumed_input", "$.evaluation_series"); err != nil {
			return err
		}
	}
	return nil
}

func requireArrayLengthMatchesNumber(arrayObject *Value, arrayField string, numberObject *Value, numberField, arrayPath, numberPath string) error {
	arrayValue, arrayOK := arrayObject.Member(arrayField)
	numberValue, numberOK := numberObject.Member(numberField)
	if !arrayOK || !numberOK || arrayValue.Kind != KindArray || numberValue.Kind != KindNumber {
		return contractError(CrossReferenceMismatch, CodeSemanticViolation, -1, numberPath+"."+numberField, fmt.Errorf("does not match %s.%s length", arrayPath, arrayField))
	}
	number, err := strconv.ParseInt(numberValue.Number, 10, 64)
	if err != nil || number != int64(len(arrayValue.Array)) {
		return contractError(CrossReferenceMismatch, CodeSemanticViolation, -1, numberPath+"."+numberField, fmt.Errorf("does not match %s.%s length", arrayPath, arrayField))
	}
	return nil
}

func validateResearchEvidenceReferences(value *Value) error {
	identity, hasIdentity := value.Member("research_identity")
	metrics, hasMetrics := value.Member("metric_results")
	if hasIdentity && hasMetrics {
		if err := requireEqualNamedString(identity, "artifact_hash", value, "evidence_id", "$.research_identity", "$"); err != nil {
			return err
		}
		series, ok := identity.Member("evaluation_series")
		if ok {
			if err := requireReferenceHash(series, "artifact_hash", metrics, "evaluation_series_hash", "$.research_identity.evaluation_series", "$.metric_results"); err != nil {
				return err
			}
		}
	}
	return nil
}

func validateResearchDiagnosticReferences(value *Value) error {
	eligible, hasEligible := value.Member("eligible_for_rif_review")
	evidence, hasEvidence := value.Member("research_evidence")
	if hasEligible && eligible.Kind == KindBoolean && eligible.Bool {
		if !hasEvidence {
			return contractError(CrossReferenceMismatch, CodeSemanticViolation, -1, "$.research_evidence", errors.New("eligible diagnostic requires research evidence"))
		}
		evidenceEligible, ok := evidence.Member("eligible_for_rif_review")
		if !ok || evidenceEligible.Kind != KindBoolean || !evidenceEligible.Bool {
			return contractError(CrossReferenceMismatch, CodeSemanticViolation, -1, "$.research_evidence.eligible_for_rif_review", errors.New("eligibility representations disagree"))
		}
	}
	return nil
}

func requireStrictlyIncreasingStringArray(object *Value, field, path string) error {
	array, ok := object.Member(field)
	if !ok || array.Kind != KindArray {
		return nil
	}
	previous := ""
	for index, item := range array.Array {
		if item.Kind != KindString || index > 0 && previous >= item.String {
			return contractError(InvalidSchema, CodeSemanticViolation, -1, fmt.Sprintf("%s[%d]", path, index), errors.New("ordered timestamp series is not strictly increasing"))
		}
		previous = item.String
	}
	return nil
}

func requireEqualString(left, right *Value, field, leftPath, rightPath string) error {
	return requireEqualNamedString(left, field, right, field, leftPath, rightPath)
}

func requireEqualNamedString(left *Value, leftField string, right *Value, rightField, leftPath, rightPath string) error {
	leftValue, leftOK := left.Member(leftField)
	rightValue, rightOK := right.Member(rightField)
	if !leftOK || !rightOK || leftValue.Kind != KindString || rightValue.Kind != KindString || leftValue.String != rightValue.String {
		return contractError(CrossReferenceMismatch, CodeReferenceHashMismatch, -1, rightPath+"."+rightField, fmt.Errorf("does not match %s.%s", leftPath, leftField))
	}
	return nil
}

func requireReferenceHash(left *Value, leftField string, right *Value, rightField, leftPath, rightPath string) error {
	return requireEqualNamedString(left, leftField, right, rightField, leftPath, rightPath)
}

func requireEqualNamedNumber(left *Value, leftField string, right *Value, rightField, leftPath, rightPath string) error {
	leftValue, leftOK := left.Member(leftField)
	rightValue, rightOK := right.Member(rightField)
	if !leftOK || !rightOK || leftValue.Kind != KindNumber || rightValue.Kind != KindNumber || leftValue.Number != rightValue.Number {
		return contractError(CrossReferenceMismatch, CodeSemanticViolation, -1, rightPath+"."+rightField, fmt.Errorf("does not match %s.%s", leftPath, leftField))
	}
	return nil
}

func withPath(err error, path string) error {
	var target *ContractError
	if errors.As(err, &target) {
		copy := *target
		copy.Path = path
		return &copy
	}
	return contractError(InvalidSchema, CodeSemanticViolation, -1, path, err)
}
